### ISSUE TITLE
Please Add Pagination...

### ISSUE THREAD

**Issue by eArabic** [whoisnian/paste#1]
**Hello my friend**
Thank you very much for sharing this beautiful script.
Please Add Pagination , And there is a search option in the posts.
As well as the possibility of Locked and sticky posts
Add a discussion feature Code: Replies
Add the Attach Files feature.
Add a share like feature.
**thank you very much**

**Comment by whoisnian** [comment]
I'm very glad to receive your issue. 
Now it is just a toy written in PHP. Maybe I need to use database to improve this site. 
And I will give this issue serious consideration. 
Thank you for your advice.

**Comment by satouriko** [comment]
Why dont you guys use something more powerful, such as [paste.gnome.org](https://paste.gnome.org/)([Source](https://github.com/sayakb/sticky-notes))
